name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t my-docker-node-app .

      - name: Run Tests (Optional)
        run: |
          # You can add any testing commands here
          echo "Run tests here"

      - name: Log in to Docker Hub (Optional)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub (Optional)
        run: |
          docker tag my-docker-node-app ${{ secrets.DOCKER_USERNAME }}/my-docker-node-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-node-app:latest

      - name: Deploy to Server (Optional)
        run: |
          # You can deploy your app here, for example, via SSH
          echo "Deploy to production server"
