name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug Docker Username
        run: echo "Docker Username is: ${{ secrets.DOCKER_USERNAME }}"

      - name: Build Docker Image
        run: docker build -t my-docker-node-app .

      - name: List Docker Images
        run: docker images

      - name: Tag Docker Image
        run: docker tag my-docker-node-app ${{ secrets.DOCKER_USERNAME }}/my-docker-node-app:latest

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-node-app:latest
